apiVersion: batch/v1
kind: Job
metadata:
  name: cpsecret
  namespace: ventress5
spec:
  template:
    metadata:
      name: cpsecret
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - "if [ -z \"$(kubectl get secret ibm-entitlement-key -n ventress5 | grep found)\" ]; \
          then kubectl get secret ibm-entitlement-key -n cp4i-eventstreams -o json \
          | jq -r '.metadata.namespace=\"ventress5\"' \
          | jq 'del(.metadata.uid, .metadata.selfLink, .metadata.ownerReferences, .metadata.resourceVersion, .metadata.creationTimestamp)'  \
          | kubectl apply -n ventress5 -f - ;\
          else echo already_created; fi"
        image: bitnami/kubectl
        name: copysecret
      restartPolicy: Never
      serviceAccountName: rt-inv-job-sa
